services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      # List of peers to connect to
      # Separate multiple peers with a comma
      - PEERS=macbookair,ipadair,iphone

      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=<YOUR_SERVER_PUBLIC_IP>
      - SERVERPORT=51820
      - INTERNAL_SUBNET=10.60.163.0
      - ALLOWEDIPS=0.0.0.0/0,::/0
    volumes:
      - ./config/:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
